AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TextractForm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 600
      Role: 'arn:aws:iam::543431917619:role/service-role/TextractForm-role-crhnv09v'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-west-2:543431917619:layer:TextractFormLayer:1'
